FLASK_DEBUG=True
FLASK_ENV=development
FLASK_RUN_PORT=8080
FLASK_RUN_HOST=127.0.0.1
FLASK_SECRET_KEY=xy3A@@aLSOQP&_#ZrygYqSfGjPR^&udWMrv8GYI-n2nAL_r-5G
FLASK_JWT_SECRET_KEY=xy3A@@aLSOQP&_#ZrygYqSfGjPR^&udWMrv8GYI-n2nAL_r-5G