"""empty message

Revision ID: 0fbb52f4a746
Revises: 631500bc9614
Create Date: 2023-11-28 21:17:51.675159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fbb52f4a746'
down_revision = '631500bc9614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('shop_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('addition_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='Дата добавления магазина в систему')
        batch_op.alter_column('api_key_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False,
               comment='Закешированный ключ API от магазина')
        batch_op.create_foreign_key(None, 'users', ['owner_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('api_key_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True,
               comment=None,
               existing_comment='Закешированный ключ API от магазина')
        batch_op.alter_column('addition_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='Дата добавления магазина в систему')
        batch_op.alter_column('shop_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
