"""test_1

Revision ID: 12c3530035a6
Revises: 
Create Date: 2023-11-27 23:57:19.845067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12c3530035a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('login')

    op.drop_table('users')
    op.drop_table('stores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('shop_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('addition_date', mysql.DATETIME(), nullable=True),
    sa.Column('api_key_hash', mysql.VARCHAR(length=512), nullable=True),
    sa.PrimaryKeyConstraint('store_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('login', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('second_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('middle_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('registration_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_login_date', mysql.DATETIME(), nullable=True),
    sa.Column('last_action_date', mysql.DATETIME(), nullable=True),
    sa.Column('test_1', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('login', ['login'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
