"""empty message

Revision ID: 48911d65f370
Revises: 0fbb52f4a746
Create Date: 2023-12-03 21:35:13.638464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48911d65f370'
down_revision = '0fbb52f4a746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
