"""empty message

Revision ID: 631500bc9614
Revises: 3387dbe4e4ed
Create Date: 2023-11-28 00:09:38.656985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '631500bc9614'
down_revision = '3387dbe4e4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
